name = "serverless-blog"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNGVhZWJmYTQtOTk1My00NzkzLTg3MjUtZTU1YzU4NzI3YmIwIiwidGVuYW50X2lkIjoiOTgzNjI3YmIyOTE1OTM0NWY3MTgwMjZmOTI2NjRmNzY4ZDFjZjAwZDAzZjY0MzJlNjljZGVjMmZkMmQ3NGU2YiIsImludGVybmFsX3NlY3JldCI6IjQzZmM1ZGNhLWI2OWItNDQ3Yi04MTY0LTViNDNlODQwZjRkOCJ9.FkuYwTLMji3gUMDYLOc7dc1sklKkkNzSfL_MSRFJUgY"
JWT_SECRET = "Thisisjwtsecret"
# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"